aemsites/vg-macktrucks-com

- blocks/v2-hero/v2-hero.css
- blocks/v2-image-banner/v2-image-banner.css
- blocks/v2-recommendations/v2-recommendations.css
- blocks/v2-recommendations/v2-recommendations.js
- blocks/v2-social-block/v2-social-block.css
- blocks/v2-social-block/v2-social-block.js
- templates/v2-magazine/v2-magazine.css
Fix #88
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-magazine-article-template
- After: https://88-template-magazine-article--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-magazine-article-template
Other markets:
Canada:
- Before: https://main--macktrucks-ca--volvogroup.aem.page/block-library/blocks/v2-magazine-article-template
- After: https://88-template-magazine-article--macktrucks-ca--volvogroup.aem.page/block-library/blocks/v2-magazine-article-template
Mexico:
- Before: https://main--macktrucks-com-mx--volvogroup.aem.page/block-library/blocks/v2-magazine-article-template
- After: https://88-template-magazine-article--macktrucks-com-mx--volvogroup.aem.page/block-library/blocks/v2-magazine-article-template
> Template: Bulldog Magazine Article #88

- blocks/dealer-locator/dealer-locator.css
- blocks/dealer-locator/sidebar-maps.js
- blocks/eloqua-form/forms/buy-mack-request-a-quote.html
- blocks/eloqua-form/forms/contact-us.html
- blocks/eloqua-form/forms/electrifi.html
- blocks/eloqua-form/forms/lr-electric-vehicle-as-a-service.html
- blocks/eloqua-form/forms/magazine-share.html
- blocks/eloqua-form/forms/magazine-subscribe.html
- blocks/header/header.css
- blocks/hero/hero.css
- blocks/inventory/inventory.css
- blocks/performance-specifications/performance-specifications.js
- blocks/v2-dealer-locator/v2-dealer-locator.css
- blocks/v2-dealer-locator/versions/default/sidebar-maps.js
- blocks/v2-dealer-locator/versions/export/sidebar-maps.js
- constants.json
- styles/lazy-styles.css
- styles/styles.css
This update swaps _Arial_ and _Helvetica_ fonts to _Inter_. 
Some `constants.json` updates must be made across all export markets to mimic this update because all classes called, e.g. `helvetica-55` and similar ones now will be called `font-55` and so on.
If there is a need to change the font linked to that CSS class again, then no more content work will be needed.
Fix #66
Test URLs:
- After: https://66-fr-change-font-css--vg-macktrucks-com--volvogroup.aem.page/
> Change fonts to Inter #66

- blocks/v2-tabbed-carousel/v2-tabbed-carousel.css
- blocks/v2-tabbed-carousel/v2-tabbed-carousel.js
Now, an author can use `text` or a `sup` element and the whole text is shown
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/wendy.kruger/bugs#superscript-in-tabbed-carousel
- After: https://69-superscript-enhancement--vg-macktrucks-com--volvogroup.aem.page/drafts/wendy.kruger/bugs#superscript-in-tabbed-carousel
> superscript enhancement in v2-tabbed-carousel #69

- blocks/dealer-locator/dealer-locator.css
- blocks/footer/footer.css
- blocks/footer/footer.js
- blocks/hotspots/hotspots.css
- blocks/v2-dealer-locator/v2-dealer-locator.css
This update removes the injection of the _scroll-to-top_ code added by the footer block. So because the footer added it, all pages are affected by this change.
#
Fix #48
Test URLs:
- After: https://48-remove-scroll-to-top-button--vg-macktrucks-com--volvogroup.aem.page/
Other markets:
Canada:
- After: https://48-remove-scroll-to-top-button--macktrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://48-remove-scroll-to-top-button--macktrucks-com-mx--volvogroup.aem.page/
> Remove Global Scroll-to-Top Button from Website #48

- blocks/header/header.css
- blocks/performance-specifications/performance-specifications.css
- blocks/v2-accordion-column/v2-accordion-column.css
- blocks/v2-accordion/v2-accordion.css
- blocks/v2-cards/v2-cards.css
- blocks/v2-columns/v2-columns.css
- blocks/v2-hero/v2-hero.css
- blocks/v2-hotspots/v2-hotspots.css
- blocks/v2-icon-cards/v2-icon-cards.css
- blocks/v2-images-grid/v2-images-grid.css
- blocks/v2-inpage-navigation/v2-inpage-navigation.css
- blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.css
- blocks/v2-newsletter/v2-newsletter.css
- blocks/v2-pencil-promo/v2-pencil-promo.css
- blocks/v2-product-listing/v2-product-listing.css
- blocks/v2-social-block/v2-social-block.css
- blocks/v2-specifications/v2-specifications.css
- blocks/v2-sub-navigation/v2-sub-navigation.css
- blocks/v2-tabbed-carousel/v2-tabbed-carousel.css
- blocks/v2-testimonial/v2-testimonial.css
- blocks/v2-truck-builder/v2-truck-builder.css
- blocks/v2-truck-lineup/v2-truck-lineup.css
- styles/styles.css
- Header (button, h4 -> `__main-link-wrapper--tabs-with-cards __category-item h3 a__link`)
- Performance Specifications (body-1 -> `.category-tab [role="tab"]`)
- V2 Accordion Column (h4 -> `__item-title`)
- V2 Accordion (h4 -> `__title`)
- V2 Cards (h5 -> `__heading`, h4 -> `--large-heading __heading`, body-1 -> `__text-wrapper p`, h4 -> `--spaced __heading`)
- V2 columns (body-1 -> `__body`, label -> `list-title`)
- V2 Hero (body-2 -> `__content 3rdLi`, body-1 -> `pdp page cta`)
- V2 Hotspots (h3 -> `hotspot h1`, h3 -> `feature-title`)
- V2 Icon Cards (body-2-bold -> `__heading Not h2`, body-2 -> `__body`, h5 -> `__heading`)
- V2 Images Grid (body-2 -> `__carousel-item p`)
- V2 Inpage Navigation (body-2 -> `__selected-item-wrapper`)
- V2 Magazine Tabbed Carousel (h4 -> `title`)
- V2 …
> CR: Inter Font Enhancements #151

- blocks/header/header.css
Fix #178
Test URLs:
- After: https://178-add-header-tab--vg-macktrucks-com--volvogroup.aem.page/
Other markets:
Canada:
- After: https://178-add-header-tab--macktrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://178-add-header-tab--macktrucks-com-mx--volvogroup.aem.page/
> FR: Navigation - Addition of an "Industry" tab section to the navigation #178

- blocks/recent-articles/recent-articles.js
In `recent-articles` block, the title had no href value making it reload the current page. The link has been added now.
Fix #223
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/magazine/categories/in-the-know
- After: https://223-bug-recent-articles--vg-macktrucks-com--volvogroup.aem.page/magazine/categories/in-the-know
> Bug: Recent articles block wrong links #223

- blocks/v2-truck-lineup/v2-truck-lineup.css
- blocks/v2-truck-lineup/v2-truck-lineup.js
- scripts/scripts.js
This update adds a new section metadata for the v2-truck-line-up block. The new key value is `Truck carousel featured` and as a value, it needs to use the keyword `active`. This highlights the featured item but keeps the list in its order.
Also, if there is more than 1 featured item, it will highlight the 1st featured item and ignore the rest.
#
Fix #185
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/lineup-demo
- After: https://185-v2-truck-lineup-enhancements--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/lineup-demo
> FR: V2 Truck Lineup - enhancements #185

- blocks/v2-picture-tooltips/v2-picture-tooltips.css
- blocks/v2-picture-tooltips/v2-picture-tooltips.js
Fix #218
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/v2-picture-tooltips-with-text
- After: https://218-picture-tooltips-text--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/v2-picture-tooltips-with-text
Test URLs of the block without the html text content:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/v2-picture-tooltips
- After: https://218-picture-tooltips-text--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/v2-picture-tooltips
> FR: Add text content to the v2-picture-tooltips block #218

- blocks/v2-pencil-promo/v2-pencil-promo.css
- blocks/v2-pencil-promo/v2-pencil-promo.js
- blocks/v2-product-listing/v2-product-listing.js
A list of Pencil Promo blocks as pencil banner variants with text must be added above the product listing block. Also, the product listing block needs a variant "_pencil promo_" to link them all. Every pencil promo block needs to add a config "segment" text to link it with the corresponding segment and, to avoid a content shift, it is essential to add also another 
pencil promo block with the config "_isFirstTab_" as _true_ to be shown at the beginning.
after check with the [query site](https://labs.aem.live/tools/site-query/index.html?org=volvogroup&site=vg-macktrucks-com) tool with the following setup:
```
query: .v2-pencil-promo
sitemap: /sitemap.xml
```
the pencil promo shows as expected in all cases
Fix #93
Test URLs:
- Before: …
> NFR: Filter Functionality for Dynamically Updating Pencil Promo Block #93

- blocks/v2-custom-form/v2-custom-form.js
Adding a 1st row to the `v2 Custom Form` block with the text (title, subtle and or regular text) makes the block know which text has to be removed when the form is submitted (successfully or with error)
#
Fix #273
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/form/title-in-block-form
- After: https://273-hide-title-after-submission--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/form/title-in-block-form
> Improvement: Hiding the "Let's talk" verbiage after a successful form submission #273

- blocks/v2-custom-form/v2-custom-form.js
To add more form validations, in the xlsx form config file, 3 more columns need to be added, such as `Pattern`, `Min` & `Max` (case sensitive btw)
~The email input type collides with a pattern attribute and the built-in pattern in the browser, so in this case, the input is changed to a text type~ it seems that now is working, so no need to change the type.
The pattern can start and end with '/', but because the last versions of Chrome check on validation if the pattern is correct, adding `/v` to the pattern, some but not all special characters need to be escaped in the pattern or the validation breaks.
I reused the same forms from issue 273, so both are sharing the same config JSON file with the new columns added
#
Fix #260
Test URLs:
- Before: …
> FR: MCAE form fields validations #260

- blocks/explore-articles/explore-articles.js
- constants.json
- package.json
- scripts/search-api.js
- scripts/services/magazine.service.js
**NOTES:** 
- This fixes the block not being able to get all articles and instead gets 100 as a default. 
- The correct way would be to modify the current one so that it only get 4 but this would take longer and the bug is in production already
- There is already a V2 block to replace this correctly but its not being used yet.
With that in mind I think its best for us to just merge this into main and decide what are the next steps regarding this page
Fix #292
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/magazine/explore-articles
- After: https://292-magazines-nz--vg-macktrucks-com--volvogroup.aem.page/magazine/explore-articles
Other markets:
New Zaeland:
- Before: https://main--macktrucks-co-nz--volvogroup.aem.page/magazine/explore-articles
- After: …
> Bug: Magazines on the Mack Trucks disappeared for the New Zealand site #292

- blocks/v2-custom-form/v2-custom-form.js
After fixing an issue to hide the title text after submitting the v2 custom form block, the block is set up to have as 1st row the title text. In the library is not set as this, so to be able to have it, this fix checks if the 1st row in the block has the config json link to add the title dynamically
#
Fix #305 
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/form/title-in-block-form
- After: https://305-form-link-is-used-as-title--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/form/title-in-block-form
Library:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-custom-form
- After: https://305-form-link-is-used-as-title--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-custom-form
> Bug: form link is used as title #305

- blocks/header/header.css
NOTE: This is actuall happening in all **non v2-redesign** pages
Fix #286 
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/search
- After: https://286-header-close-btn--vg-macktrucks-com--volvogroup.aem.page/search
Other markets:
Canada:
- Before: https://main--macktrucks-ca--volvogroup.aem.page/search
- After: https://286-header-close-btn--macktrucks-ca--volvogroup.aem.page/search
Mexico has no search page so instead this can be used:
- Before: https://main--macktrucks-com-mx--volvogroup.aem.page/magazine/
- After: https://286-header-close-btn--macktrucks-com-mx--volvogroup.aem.page/magazine/
> Bug: white close button on header in search page at mobile viewport #286

- scripts/scripts.js
Fix #100
Test URLs:
- After: https://100-html-lang-settings--vg-macktrucks-com--volvogroup.aem.page/
Other markets:
Canada:
- After: https://100-html-lang-settings--macktrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://100-html-lang-settings--macktrucks-com-mx--volvogroup.aem.page/
> NFR: Language setting needs to be applied to all website - MT #100

- common/modal/modal-component.js
Fix #310 
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/powertrain-and-suspensions/transmissions/mdrive/
- After: https://310-play-modal-with-sound--vg-macktrucks-com--volvogroup.aem.page/powertrain-and-suspensions/transmissions/mdrive/
Also from the previous PR:
Test URLs:
Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-columns
After: https://310-play-modal-with-sound--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-columns
Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-embed
After: …
> FR: Add Custom Mute/Unmute button  #310

- blocks/v2-hero/v2-hero.css
new background color -> in section metadata, as a _style_ add a regular _gray background_ key word as usual
added half of an aspect ratio from 16 / 9 to 32 / 9 In the desktop viewport ( > 1200px)
#
Fix #70
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/v2-hero-half-height
- After: https://70-new-hero-half-height--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/v2-hero-half-height
> FR: [V2 Hero Half-height] Enhancements #70

- blocks/header/header.css
- blocks/header/header.js
Fix #219
Note: the left alignment applies only on desktop.
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alan/nav-logo-left
- After: https://219-header-update--vg-macktrucks-com--volvogroup.aem.page/drafts/alan/nav-logo-left
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alan/nav-logo-left-no-button
- After: https://219-header-update--vg-macktrucks-com--volvogroup.aem.page/drafts/alan/nav-logo-left-no-button
Added a note explaining how to place the logo to the left:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/header-and-navigation
- After: https://219-header-update--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/header-and-navigation
> FR: Update custom header component #219

- scripts/delayed.js
This update integrates the maze script into the delayed.js script. It is the only third-party script that is not filtered by cookies. Also, I follow the same pattern that Alexis did in RC, adding all the conditionals to load the scripts in a single function call called `delayedInit`
#
Fix #49
Test URLs:
- After: https://49-maze-integration-poc--vg-macktrucks-com--aemsites.aem.page/
Other markets:
Canada:
- After: https://49-maze-integration-poc--macktrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://49-maze-integration-poc--macktrucks-com-mx--volvogroup.aem.page/
> NFR: Request for Maze Integration for Usability Testing PoC #49

- blocks/dealer-locator/sidebar-maps.js
- blocks/v2-dealer-locator/v2-dealer-locator.css
- blocks/v2-dealer-locator/versions/default/sidebar-maps.js
- blocks/v2-dealer-locator/versions/export/sidebar-maps.js
- blocks/v2-hero/v2-hero.css
- styles/styles.css
Although not all markets are listed below, this change will affect all of them. I added just the 3 main ones and some other examples that are different from each other.
Also fixed the hover effect on the pins so that the scaled version stays on point
Fix #390 
USA (should be miles by default):
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/buy-mack/find-a-dealer/
- After: https://390-distance-calc--vg-macktrucks-com--volvogroup.aem.page/buy-mack/find-a-dealer/
Canada:
- Before: https://main--macktrucks-ca--volvogroup.aem.page/buy-mack/find-a-dealer/
- After: https://390-distance-calc--macktrucks-ca--volvogroup.aem.page/buy-mack/find-a-dealer/
Mexico:
- Before: https://main--macktrucks-com-mx--volvogroup.aem.page/buy-mack/find-a-dealer/
- After: …
> Bug: Web version of the Dealer Locator shows incorrect distance #390

- blocks/v2-recommendations/v2-recommendations.css
- blocks/v2-recommendations/v2-recommendations.js
- scripts/search-api.js
- scripts/services/magazine.service.js
- scripts/video-helper.js
Fix #72
For testing purposes, a `video-url` property was added to the metadata of the following two pages. These should be removed once testing is complete:
- [AEM assets video](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B9C93632D-D65E-4213-93A6-8494758C907C%7D&file=mack-defense-powers-military-with-next-gen-tactical-trucks.docx&action=default&mobileredirect=true).
- [MP4 video](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B30FB7A45-B798-4988-A89C-9C25C29D15DC%7D&file=mack-drives-sustainability-with-smarter-greener-trucks.docx&action=default&mobileredirect=true).
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-recommendations
- After: …
> FR: V2 Recommendations block with video  #72

- blocks/v2-truck-lineup/v2-truck-lineup.js
Now it is not needed to add any dirty workaround to the link to make it not a button. For comparison, I left the demo page and the current one that still has the dot in a single link
#
Fix #65 
Test URLs:
With the dot (scroll to the truck line up)
- After: https://65-v2-trucks-lineup--vg-macktrucks-com--volvogroup.aem.page/
without the dot
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/lineup-demo
- After: https://65-v2-trucks-lineup--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/lineup-demo
> Bug: [v2-trucks-lineup] #65

- blocks/v2-dealer-locator/v2-dealer-locator.css
- blocks/v2-dealer-locator/versions/default/sidebar-maps.js
- blocks/v2-dealer-locator/versions/export/sidebar-maps.js
Also added an opacity layer to the active/disabled filters for clearer interaction.
**NOTE**: export markets dont have these filters since all dealers are listed as "dealers" only not uptime or electric.
Fix #311 
USA (should be miles by default):
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/buy-mack/find-a-dealer/
- After: https://311-dist-toggle--vg-macktrucks-com--volvogroup.aem.page/buy-mack/find-a-dealer/
Canada:
- Before: https://main--macktrucks-ca--volvogroup.aem.page/buy-mack/find-a-dealer/
- After: https://311-dist-toggle--macktrucks-ca--volvogroup.aem.page/buy-mack/find-a-dealer/
Mexico:
- Before: https://main--macktrucks-com-mx--volvogroup.aem.page/buy-mack/find-a-dealer/
- After: https://311-dist-toggle--macktrucks-com-mx--volvogroup.aem.page/buy-mack/find-a- …
> Bug: Issue with km/mi toggle on V2 Dealer Locator block #311

- blocks/vin-number/vin-number.js
- placeholder.json
Fix #441
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/recalls/
- After: https://441-vin-issue-date--vg-macktrucks-com--volvogroup.aem.page/recalls/
Tested locally with vin 1M2AN9GY0PM001220
> Transport Canada: Add "Transport Canada Issue Date“ [Mack-English] #441

- blocks/vin-number/vin-number.js
NOTE: the `/recalls-fr/` page seems unnecessary since it has mixed wording and we already have 2 other pages linked with correct languages
Fix #446 
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/recalls/
- After: https://446-date-display--vg-macktrucks-com--volvogroup.aem.page/recalls/
Other markets:
Canada:
FRENCH
- Before: https://main--macktrucks-ca--volvogroup.aem.page/fr-ca/recalls/
- After: https://446-date-display--macktrucks-ca--volvogroup.aem.page/fr-ca/recalls/
ENGLISH
- Before: https://main--macktrucks-ca--volvogroup.aem.page/recalls/
- After: https://446-date-display--macktrucks-ca--volvogroup.aem.page/recalls/
> Transport Canada: Enable date display for "Information last updated" on MT CA Recalls Eng and Fr pages #446
