- .github/workflows/old-publish-notifier.yaml
- .github/workflows/old-unpublish-notifier.yaml
- .github/workflows/publish-notifier.yaml
Fix #878
Replaces wrong PR https://github.com/aemsites/vg-macktrucks-com/pull/8
Test URLs:
- After: https://878-search-add-search-connectors-old-and-new--vg-macktrucks-com--volvogroup.aem.page/
> 878 search add search connectors old and new

- .github/pull_request_template.md
- tools/sidekick/config.json
- tools/sidekick/library.css
- tools/sidekick/library.html
- tools/sidekick/library.js
Also added a new PR format with other markets included (mexico and canada)
Fix #26 
Test URLs:
- After: https://26-library-fix--vg-macktrucks-com--volvogroup.aem.page/
> Block Library config updated #26

- README.md
- blocks/v2-category-collage/v2-category-collage.js
Fix #13
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-category-collage
- After: https://13-fix-v2-category-collage--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-category-collage
> Fix v2 category collage #13

- blocks/v2-navigation-hub/v2-navigation-hub.css
Fix #16
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-navigation-hub
- After: https://16-fix-v2-navigation-hub--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-navigation-hub
> Fix v2 navigation hub #16

- blocks/v2-cards/v2-cards.css
Fix #17
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/wendy.kruger/bugs#v2-cards:~:text=Issues,-with%20v2%20cards
- After: https://17-fix-v2-cards--vg-macktrucks-com--volvogroup.aem.page/drafts/wendy.kruger/bugs#v2-cards:~:text=Issues,-with%20v2%20cards
> Fix v2 cards #17

- blocks/v2-columns/v2-columns.css
- blocks/v2-columns/v2-columns.js
Fix #19
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-columns
- After: https://19-fix-v2-columns--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-columns
> Fix v2-columns #19

- blocks/v2-magazine-tabbed-carousel/v2-magazine-tabbed-carousel.css
Fix #15
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-magazine-tabbed-carousel
- After: https://15-fix-v2-magazine-tab--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-magazine-tabbed-carousel
> Fix v2 magazine tab #15

- blocks/dealer-locator/dealer-locator.js
- blocks/header/header.js
- blocks/magazine-subscribe/magazine-subscribe.js
- blocks/search/search-api.js
- blocks/v2-dealer-locator/v2-dealer-locator.js
- scripts/common.js
- scripts/delayed.js
- scripts/scripts.js
- scripts/validate-countries.js
- scripts/validate-elements.js
Fix #36
Add extra layers of checks and move to the proper place some variables to avoid executing them always.
Now, if any of the constants values is missing, the function that need that value doesn't execute at all
Test URLs:
- After: https://36-failsafe-for-constants-config--vg-macktrucks-com--volvogroup.aem.page/
Other markets:
Canada:
- After: https://36-failsafe-for-constants-config--macktrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://36-failsafe-for-constants-config--macktrucks-com-mx--volvogroup.aem.page/
> add failsafes for config data from constants.json file #36

- blocks/v2-hotspots/v2-hotspots.js
Fix #43
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/powertrain-and-suspensions/engines/mp8/
- After: https://43-v2-hotspots-fix-carousel--vg-macktrucks-com--volvogroup.aem.page/powertrain-and-suspensions/engines/mp8/
> Bug: Modal Carousel Not Displaying All Hotspot Cards #43

- blocks/footer/footer.js
- blocks/fragment/fragment.js
- blocks/v2-forms/v2-forms.js
- blocks/v2-newsletter/v2-newsletter.js
- scripts/aem.js
- scripts/common.js
- scripts/delayed.js
- scripts/scripts.js
- scripts/video-helper.js
Fix #12 
Fix #126 
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/magazine-subscribe
- After: https://12-update-scripts--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/magazine-subscribe
> Update aem.js scripts #12

- blocks/news-list/news-list.js
- blocks/news-sidebar/news-sidebar.js
- blocks/search/search-api.js
- blocks/v2-hotspots/v2-hotspots.js
- scripts/common.js
- scripts/news.js
Reverts aemsites/vg-macktrucks-com#129
> Revert "Add news feed configs #104"

- templates/magazine/magazine.js
Fix #137 
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/magazine/articles/2022/august/closer-look-mack-md
- After: https://<branch>--vg-macktrucks-com--volvogroup.aem.page/magazine/articles/2022/august/closer-look-mack-md
> Fix magazine subscribe form #137

- blocks/explore-articles/explore-articles.js
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/magazine/explore-articles
- After: https://FIX-explore-articles-counter--vg-macktrucks-com--volvogroup.aem.page/magazine/explore-articles
Canada:
- Before: https://main--macktrucks-ca--volvogroup.aem.page/magazine/explore-articles
- After: https://FIX-explore-articles-counter--macktrucks-ca--volvogroup.aem.page/magazine/explore-articles
> Fix counter for magazine-explore block

- scripts/common.js
- scripts/scripts.js
Fix #147
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/trucks/anthem/
- After: https://147-fix-v2-inpage-nav--vg-macktrucks-com--volvogroup.aem.page/trucks/anthem/
> Fix v2-inpage-navigation load #147

- blocks/v2-hero/v2-hero.js
Fix #150
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alan/v2-hero-video
- After: https://150-hero-with-video-button--vg-macktrucks-com--volvogroup.aem.page/drafts/alan/v2-hero-video
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-hero
- After: https://150-hero-with-video-button--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-hero
> Hero with video button #150

- blocks/v2-explore-articles/v2-explore-articles.css
- blocks/v2-explore-articles/v2-explore-articles.js
- placeholder.json
- scripts/services/magazine.service.js
Fix #39 
Test URLs:
Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/v2-explore-articles
After: https://39-sort-toggle--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/v2-explore-articles
Other markets:
Canada:
Before: https://main--macktrucks-ca--volvogroup.aem.page/drafts/shomps/v2-explore-articles
After: https://39-sort-toggle--macktrucks-ca--volvogroup.aem.page/drafts/shomps/v2-explore-articles
> FR: "Most Recent" and "Alphabetical" order toggle - FE work #39

- blocks/v2-hero/v2-hero.css
- blocks/v2-hero/v2-hero.js
Fix #145
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alan/v2-hero
- After: https://145-countdown-form--vg-macktrucks-com--volvogroup.aem.page/drafts/alan/v2-hero
> Countdown - Contact form (2 of 4) #145

- blocks/header/header.css
- blocks/header/header.js
Fix #179
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alan/homepage/
- After: https://179-nav-new-truck--vg-macktrucks-com--volvogroup.aem.page/drafts/alan/homepage/
> Navigation - Mack Mega Menu Change #179

- blocks/dealer-locator/dealer-locator.js
- blocks/v2-dealer-locator/v2-dealer-locator.js
- blocks/v2-icon-cards/v2-icon-cards.css
- blocks/v2-icon-cards/v2-icon-cards.js
- common/countdown/countdown.css
- scripts/common.js
Fix #184
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/v2-icon-cards-sliders
- After: https://184-icon-card-slider--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/v2-icon-cards-sliders
- Block Library: https://184-icon-card-slider--vg-macktrucks-com--volvogroup.aem.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-icon-cards&index=16
> FR: PDP Feature Benefit Slider - V2 Icon Card variant #184

- blocks/hero/hero.css
- blocks/v2-hero-reveal/v2-hero-reveal.css
- blocks/v2-hero-reveal/v2-hero-reveal.js
- blocks/v2-hero/v2-hero.css
- blocks/v2-hero/v2-hero.js
- blocks/v2-hotspots/v2-hotspots.css
- common/countdown/countdown.css
- common/modal/modal-component.css
- package-lock.json
- package.json
- scripts/video-helper.js
- styles/lazy-styles.css
- styles/styles.css
Fix #154
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/reveal/reveal-1
- After: https://154-countdown-in-hero--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/reveal/reveal-1
- 
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/reveal/reveal-2
- After: https://154-countdown-in-hero--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/reveal/reveal-2
- 
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/reveal/v2-hero-reveal
- After: https://154-countdown-in-hero--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/reveal/v2-hero-reveal
- 
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/reveal/reveal-last
- After: …
> FR: Countdown in hero - content displayed / restream integration (3 of 4) #154

- blocks/dealer-locator/dealer-locator.js
- blocks/performance-specifications/performance-specifications.js
- blocks/v2-custom-form/v2-custom-form.css
- blocks/v2-image-banner/v2-image-banner.css
- blocks/v2-picture-tooltips/v2-picture-tooltips.css
- blocks/v2-picture-tooltips/v2-picture-tooltips.js
- blocks/v2-recommendations/v2-recommendations.css
- blocks/v2-stories-carousel/v2-stories-carousel.css
- common/modal/modal-component.css
- placeholder.json
- scripts/common.js
- styles/lazy-styles.css
- styles/styles.css
Fix #183
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-picture-tooltips
- After: https://183-v2-picture-tooltips--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-picture-tooltips
> FR: V2-columns functionality for Hotspot with Tooltip #183

- blocks/header/header.css
- blocks/header/header.js
- blocks/v2-columns/v2-columns.js
- blocks/v2-product-listing/v2-product-listing.css
- blocks/v2-product-listing/v2-product-listing.js
- scripts/common.js
- styles/styles.css
Fix #193
Test URLs:
**HEADER**
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/homepage/
- After: https://193-new-label--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/homepage/
**V2 PRODUCT LISTING**
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/homepage/
- After: https://193-new-label--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/v2-product-listing
**V2 COLUMNS** (MISSING)
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/v2-columns
- After: https://193-new-label--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/v2-columns
> FR: Add label to menus and blocks #193

- blocks/v2-feature-carousel/v2-feature-carousel.css
- blocks/v2-feature-carousel/v2-feature-carousel.js
Added the possibility to have multiple images in the feature carousel. The action of the carousel is only engaged by the buttons or, for mobile, scrolling the cards with text.
Fix #190
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/v2-feature-carousel
- After: https://190-feature-carousel--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/v2-feature-carousel
Block library URL:
/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-feature-carousel&index=0
> FR: V2 Feature Carousel - Slider variant image and content #190

- blocks/v2-embed/v2-embed.js
Fix #182
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-embed
- After: https://182-v2-embed-options--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-embed
> V2 Embed - Stylized play button in top right corner #182

- blocks/v2-custom-form/v2-custom-form.css
- blocks/v2-custom-form/v2-custom-form.js
Add styles for checkboxes to be like the ones in Eloqua iframe blocks
#
Fix #253
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/form/let-s-talk
- After: https://253-add-check-box-to-forms--vg-macktrucks-com--volvogroup.aem.page/drafts/jlledo/form/let-s-talk
> Task: Add Check box to forms #253

- scripts/video-helper.js
Fix #265
Test URLs:
- After: https://265-video-playback-ios--vg-macktrucks-com--volvogroup.aem.page/
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-video
- After: https://265-video-playback-ios--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-video
> Custom playback button not working on iOS #265

- blocks/footer/footer.js
- blocks/header/header.js
- styles/styles.css
Fix #270
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/info/driven-by-heroes
- After: https://270-add-failsafe-code--vg-macktrucks-com--volvogroup.aem.page/info/driven-by-heroes
> Add failsafe code for header and footer #270

- common/custom-dropdown/custom-dropdown.css
Fix #269
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/forms/v2-custom-form2
- After: https://269-dropdown-text-color--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/forms/v2-custom-form2
> Bug: V2 form block has white text on white background in the dropdowns #269

- blocks/v2-custom-form/v2-custom-form.js
- styles/styles.css
Fix #308
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-custom-form
- After: https://308-honeypot-field--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-custom-form
> FR: Add honeypot field to V2 Custom Form block detect bot submission #308

- blocks/v2-custom-form/v2-custom-form.css
- blocks/v2-custom-form/v2-custom-form.js
- common/custom-dropdown/custom-dropdown.css
Fix #309 
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/form/form-with-dependent-fields
- After: https://309-dependent-inputs--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/form/form-with-dependent-fields
> FR: Dropdown for state selection in V2 Custom Form - MT #309

- blocks/v2-custom-form/v2-custom-form.css
- blocks/v2-custom-form/v2-custom-form.js
- common/custom-dropdown/custom-dropdown.css
Fix #302
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alan/v2-custom-form
- After: https://302-form-radio-buttons--vg-macktrucks-com--volvogroup.aem.page/drafts/alan/v2-custom-form
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-custom-form
- After: https://302-form-radio-buttons--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-custom-form
> FR: Add Radio buttons to the V2 Custom Form block - MT #302

- blocks/v2-custom-form/v2-custom-form.js
Fix #328 
Test URLs:
- Before: https://develop--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/form/form-with-dependent-fields
- After: https://328-dont-send-hidden-fields--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/form/form-with-dependent-fields
> FR: v2-custom-form don't send on submit the hidden fields that are dependent on another input field value #328

- scripts/delayed.js
- scripts/scripts.js
- scripts/video-helper.js
Fix #263
Test URLs:
- After: https://263-videojs-loading--vg-macktrucks-com--volvogroup.aem.page/
> NFR: Improve the loading of AEM asset videos and the Video.js library #263

- blocks/v2-icon-cards/v2-icon-cards.css
Fix #318 
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/nagaraj/v2-icon-cards
- After: https://318-vertical-spacing-icon-cards--vg-macktrucks-com--volvogroup.aem.page/drafts/nagaraj/v2-icon-cards
> FR: Add vertical margins to v2 icon cards row #318

- blocks/header/header.js
- blocks/v2-custom-form/v2-custom-form.css
- blocks/v2-custom-form/v2-custom-form.js
- blocks/v2-dealer-locator/versions/default/sidebar-maps.js
- blocks/v2-specifications/v2-specifications.js
- blocks/v2-truck-lineup/v2-truck-lineup.js
- common/custom-dropdown/custom-dropdown.css
- mack-news/com/feed.xml
- mack-news/museum/feed.xml
- package-lock.json
- package.json
- scripts/common.js
- scripts/delayed.js
- scripts/scripts.js
- scripts/video-helper.js
- styles/styles.css
Test URLs:
- After: https://release-41--vg-macktrucks-com--volvogroup.aem.page/
Other markets:
Canada:
- After: https://release-41--macktrucks-ca--volvogroup.aem.page/
Mexico:
- After: https://release-41--macktrucks-com-mx--volvogroup.aem.page/
> Release 41

- blocks/performance-specifications/performance-specifications.css
- blocks/performance-specifications/performance-specifications.js
- styles/styles.css
Fix #240
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/performance-specifications/mp13/
- After: https://240-chart-updates--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/performance-specifications/mp13/
> FR: Chart engine for the Performance Specifications block #240

- blocks/v2-feature-carousel/v2-feature-carousel.css
- blocks/v2-feature-carousel/v2-feature-carousel.js
- scripts/video-helper.js
#321 
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/v2-feature-slider-with-video
- After: https://321-featured-carousel-video--vg-macktrucks-com--volvogroup.aem.page/drafts/alexis/v2-feature-slider-with-video
> FR: V2 Feature Carousel - Add capability to use background video  #321

- blocks/v2-hero/v2-hero.css
- blocks/v2-hero/v2-hero.js
- styles/styles.css
Fix #91
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/v2-hero
- After: https://91-hero-variant--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/v2-hero
Test URLs BLOCK LIBRARY:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-hero
- After: https://91-hero-variant--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-hero
>  FR: V2 Hero create new variant for secondary PDP #91

- styles/styles.css
NOTE: THIS IS A COPY OF THIS [PR](https://github.com/aemsites/vg-macktrucks-com/pull/347) BUT THE BRANCH NAME WAS TOO LONG SO I CHANGED TO MAKE THE TEST PAGE WORK
Fix https://github.com/aemsites/vg-macktrucks-com/issues/346
Test URLs:
Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/wendy.kruger/blocks/video
After: https://346-videos--vg-macktrucks-com--volvogroup.aem.page/drafts/wendy.kruger/blocks/video
> FR: Enhance/style videojs big play button #346 #347

- blocks/header/header.css
Fix #344 
Test URLs:
- After: https://344-bug-megamenu--vg-macktrucks-com--volvogroup.aem.page/
Other markets:
> Bug: Megamenu featured card content missing #344

- common/modal/modal-component.css
- styles/styles.css
The text is set below the video, and the play and mute buttons are set correctly and with the correct colors on the v1 page
#
Fix #337
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/parts-and-services/fleet/mack-fleetpreferred/
- After: https://337-cookie-banner-bug--vg-macktrucks-com--volvogroup.aem.page/parts-and-services/fleet/mack-fleetpreferred/
v2 testimonial Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-testimonial
- After: https://337-cookie-banner-bug--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-testimonial
v2 icon cards Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-icon-cards
- After: …
> Bug: Cookie banner fails to render correctly when opening video in modal #337

- blocks/v2-truck-lineup/v2-truck-lineup.css
- blocks/v2-truck-lineup/v2-truck-lineup.js
Fix #90 
Test URLs **(2 images)**:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/v2-truck-lineup
- After: https://90-truck-lineup--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/v2-truck-lineup
Library **(2 image)**:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-truck-lineup
- After: https://90-truck-lineup--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-truck-lineup
Original block **(1 image)** this should'nt be affected:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page
- After: https://90-truck-lineup--vg-macktrucks-com--volvogroup.aem.page
> FR: Mobile Trucks lineup carousel enhancement #90

- blocks/performance-specifications/performance-specifications.js
- placeholder.json
Fix #382
Test URLs:
**with 4 lines**
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/performance-specifications/mp13b/
- After: https://382-graph-4-lines--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/performance-specifications/mp13b/
**with 2 lines**
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/performance-specifications/mp13/
- After: https://382-graph-4-lines--vg-macktrucks-com--volvogroup.aem.page/drafts/shomps/performance-specifications/mp13/
> FR: Display engine performance graph with four lines (2 of 2) #382

- blocks/v2-cards/v2-cards.css
- blocks/v2-cards/v2-cards.js
Fix #419
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/rishav/bulldog-magazine-test
- After: https://419-enhance-img-quality-v2-cards--vg-macktrucks-com--volvogroup.aem.page/drafts/rishav/bulldog-magazine-test
Block library
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/tools/sidekick/library.html?theme=light&plugin=blocks&path=/block-library/blocks/v2-cards&index=15
- After: https://419-enhance-img-quality-v2-cards--vg-macktrucks-com--volvogroup.aem.page/tools/sidekick/library.html?theme=light&plugin=blocks&path=/block-library/blocks/v2-cards&index=15
> FR: Enhance Image quality in the V2 cards block

- blocks/header/header.js
- package-lock.json
Fix #519
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/recalls/
- After: https://519-js-header-error--vg-macktrucks-com--volvogroup.aem.page/recalls/
> Fix header js error #519

- placeholder.json
Fix #440
Test URLs:
- Before: https://main--vg-macktrucks-com--volvogroup.aem.page/recalls/
- After: https://440-nhtsa-label--vg-macktrucks-com--volvogroup.aem.page/recalls/
>  Transport Canada: Rename "Issue Date" to "NHTSA Issue Date" (Mack-English) #440
